nelmio_api_doc:
    documentation:
        info:
            title: Ticket To Ride Scoring API
            description: This API return score for differents destinations of the game Ticket To Ride !
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
