version: '3'

services:
  mysql:
    image: mysql:5.6.40
    container_name: mysql_ticket_to_ride
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql:/var/lib/mysql
    restart:
      always


volumes:
  mysql: